<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Booking</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">


    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="./css_for_confirm.css">

</head>

<body>
    <!-- partial:index.partial.html -->
    <div class="box-form">
        <div class="left">
            <div class="overlay">
                <pre>                                                                             </pre>
                <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
                <!-- <h1>Pay now to confirm your tickets!!</h1>
                <form>
                    <script src="https://checkout.razorpay.com/v1/payment-button.js"
                        data-payment_button_id="pl_KGwhORAbR1ljYD" async> </script>

                </form> -->
                <script src="https://code.jquery.com/jquery-3.5.0.js">

                </script>
                <form action="insertticket.php" method="POST">
                    <script
                        src="https://checkout.razorpay.com/v1/checkout.js"
                        data-key="rzp_test_ceQXrIOlYTHTPJ" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
                        data-amount="50000" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
                        data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
                        data-order_id="<?php 'OID'.rand(10,100).'END'?>"// Replace with the order_id generated by you in the backend.
                        data-buttontext="Pay with Razorpay"
                        data-name="Gitam Open Auditorium"
                        data-description="Testing Phase"
                        data-image="websiteimages/logo.jpg"
                        data-prefill.name="Habeeb"
                        data-prefill.email="121910305006@gitam.in"
                        data-theme.color="#F37254"
                    ></script>
                    <input type="hidden" custom="Hidden Element" name="hidden">
                    </form>

                <style>
                    .razorpay-payment-button {display : none;}
                </style>
                        <script type="text/javascript">
                        $(window).on('load', function(){
                            $('.razorpay-payment-button').click();
                        });
                        </script>
            </div>
        </div>
    </div>
    <?php 
    
    ?>
</body>

</html>